sudo: enabled
dist: trusty
services:
  - docker 
language: go
go:
  - 1.7
before_install:
  - sudo apt-get update
  - sudo apt-get install -y docker-engine liblxc1 lxc-dev lxc
script:
  - make host
notifications:
  email:
    recipients:
- maheshreddy7797@gmail.com 
